project_name: ratelimiter

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X internal/version.version={{ .Version }}
      - -X internal/version.commitHash={{ .ShortCommit }}
      - -X internal/version.buildDate={{ .Date }}
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm

archives:
  - format: tar.gz
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}.sha256sum"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: khos2ow
    name: ratelimiter
  footer: |
    ## Docker images

    - `docker pull khos2ow/ratelimiter:latest`
    - `docker pull khos2ow/ratelimiter:{{ .RawVersion }}`

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - dockerfile: scripts/release/Dockerfile
    use: buildx
    goarch: amd64
    image_templates:
      - "khos2ow/ratelimiter:latest-amd64"
      - "khos2ow/ratelimiter:{{ .RawVersion }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
  - dockerfile: scripts/release/Dockerfile
    use: buildx
    goarch: arm64
    image_templates:
      - "khos2ow/ratelimiter:latest-arm64"
      - "khos2ow/ratelimiter:{{ .RawVersion }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "khos2ow/ratelimiter:latest"
    image_templates:
      - "khos2ow/ratelimiter:latest-amd64"
      - "khos2ow/ratelimiter:latest-arm64"
  - name_template: "khos2ow/ratelimiter:{{ .RawVersion }}"
    image_templates:
      - "khos2ow/ratelimiter:{{ .RawVersion }}-amd64"
      - "khos2ow/ratelimiter:{{ .RawVersion }}-arm64"
