project_name: ratelimiter

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X internal/version.version={{ .Version }}
      - -X internal/version.commitHash={{ .ShortCommit }}
      - -X internal/version.buildDate={{ .Date }}
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
      - arm
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Tag }}.sha256sum"

dockers:
  - dockerfile: scripts/release/Dockerfile
    image_templates:
      - "khos2ow/ratelimiter:latest"
      - "khos2ow/ratelimiter:{{ .RawVersion }}"

brews:
  - tap:
      owner: khos2ow
      name: homebrew-tap
    commit_author:
      name: khos2ow
    url_template: "https://github.com/khos2ow/ratelimiter/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/khos2ow/"
    description: "Distributed rate limiting in Go"
    test: |
      system "#{bin}/ratelimiter version"

scoop:
  bucket:
    owner: khos2ow
    name: scoop-bucket
  commit_author:
    name: khos2ow
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  url_template: "https://github.com/khos2ow/khos2ow/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  homepage: "https://github.com/khos2ow/"
  description: "Distributed rate limiting in Go"
  license: Apache-2.0

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
