---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rate-limiter-config
  namespace: rate-limiter
  labels:
    app: rate-limiter
data:
  REDIS_URL: "<REDIS.URL>"
  REDIS_PORT: "<REDIS.PORT>"
  BACKEND_SERVER: ""
  # BACKEND_SERVER: "<COMMA.SEPARATED.BACKEND.SERVERS>"
