---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rate-limiter
  labels:
    app: rate-limiter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rate-limiter
  labels:
    app: rate-limiter
rules:
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rate-limiter
  labels:
    app: rate-limiter
subjects:
  - kind: ServiceAccount
    name: rate-limiter
    namespace: rate-limiter
roleRef:
  kind: Role
  name: rate-limiter
  apiGroup: rbac.authorization.k8s.io
