name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run tests
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.out

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binary for current OS/ARCH
      run: make build

  docker:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build 'dev' Docker image
      if: "!contains(github.ref, 'refs/heads/master')"
      run: DOCKER_TAG=${{ github.sha }} make docker

    - name: Build and push 'edge' Docker image
      if: "contains(github.ref, 'refs/heads/master')"
      run: |
        echo ${REGISTRY_PASSWORD} | docker login -u ${REGISTRY_USERNAME} --password-stdin
        DOCKER_TAG=edge make docker push
      env:
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
