name: release

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

jobs:
  assets:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
