name: release

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

jobs:
  assets:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build binaries for all OS/ARCH platforms
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make gox build-all

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/ratelimiter-v*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Set version output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF:11} # tag name without leading 'v'

    - name: Build and push Docker image
      run: |
        echo ${REGISTRY_PASSWORD} | docker login -u ${REGISTRY_USERNAME} --password-stdin
        DOCKER_TAG=${{ steps.vars.outputs.tag }} make image push
        DOCKER_TAG=latest make image push
      env:
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
