name: release

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

env:
  GO_VERSION: "1.16"
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}

jobs:
  assets:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Login to Docker
        uses: docker/login-action@v1.10.0
        if: env.REGISTRY_USERNAME != ''
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.0
        if: env.REGISTRY_USERNAME != ''
        with:
          version: latest
          args: release --rm-dist --skip-sign
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}

      - name: Clean up
        if: always()
        run: rm -f ${HOME}/.docker/config.json
