name: validate

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Verify 'vendor' dependencies
      run: make verify

  checkfmt:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Check formatting of go files
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make goimports checkfmt

  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Set up Go 1.14.x
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run linters
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make golangci lint
